www/api/urls.py
from rest_framework import routers
from api import views


router = routers.DefaultRouter()
router.register(r'recipes', views.RecipeViewSet, basename='recipes')
router.register(r'elements', views.ElementViewSet)

urlpatterns = router.urls

www/recipes/urls.py
from django.urls import path

from recipes import views

urlpatterns = [
    path('', views.RecipeListView.as_view(), name='list'),
    path('<slug:slug>/<int:pk>/', views.RecipeDetailView.as_view(), name='detail'),
]

www/www/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('', include(('recipes.urls', 'recipes'), namespace='recipes')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

www/recipes/models.py
from django.conf import settings
from django.db import models
from django.db.models import F
from django.utils.functional import cached_property
from django.utils.text import slugify
from rest_framework.reverse import reverse as reverse_drf
from versatileimagefield.fields import VersatileImageField, PPOIField


class Tag(models.Model):
    name = models.CharField(unique=True, max_length=100)
    slug = models.SlugField(unique=True, max_length=100)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='recipes')
    name = models.CharField(max_length=255)
    image = VersatileImageField(upload_to='recipe', null=True, ppoi_field='ppoi')
    ppoi = PPOIField()
    content = models.TextField()
    preparation_time = models.SmallIntegerField()
    added = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    is_visible = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    is_draft = models.BooleanField(default=False)
    tags = models.ManyToManyField('recipes.Tag', related_name='recipes', blank=True)

    class Meta:
        ordering = ['id', ]

    def __str__(self):
        return self.name

    @cached_property
    def slug(self):
        return slugify(self.name)

    def get_absolute_url(self):
        return '/{}/{}/'.format(self.slug, self.id)

    @cached_property
    def url(self):
        return reverse_drf('api:recipes-detail', args=[self.id])

    @cached_property
    def author_name(self):
        return self.author.get_full_name()

    @cached_property
    def ingredients(self):
        return self.ingredient_set.all()

    @cached_property
    def ingredients_json(self):
        return self.ingredient_set.annotate(
            element_name=F('element__name'), quantity_name=F('quantity__name')
        ).values('element_name', 'quantity_name', 'amount')

    @cached_property
    def element_slugs(self):
        return [ingredient.element.slug for ingredient in self.ingredients]


class Section(models.Model):
    recipe = models.ForeignKey('recipes.Recipe', on_delete=models.CASCADE)
    image = VersatileImageField(upload_to='sections', blank=True, ppoi_field='ppoi')
    ppoi = PPOIField()
    title = models.CharField(max_length=255, blank=True)
    content = models.TextField(blank=True)
    order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta:
        ordering = ['order', ]

    def __str__(self):
        return '{} {}'.format(self.recipe, self.order)


class Quantity(models.Model):
    name = models.CharField(max_length=32)
    last_modified = models.DateTimeField(auto_now=True)
    order = models.PositiveIntegerField(default=0, blank=False, null=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "quantities"
        ordering = ['order', ]


class Element(models.Model):
    name = models.CharField(max_length=32)
    quantity = models.ManyToManyField('recipes.Quantity', related_name='quantities')
    last_modified = models.DateTimeField(auto_now=True)
    order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.name

    @cached_property
    def slug(self):
        return slugify(self.name)


class Ingredient(models.Model):
    recipe = models.ForeignKey('recipes.Recipe', on_delete=models.CASCADE)
    element = models.ForeignKey('recipes.Element', on_delete=models.CASCADE)
    quantity = models.ForeignKey('recipes.Quantity', on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    order = models.PositiveIntegerField(default=0, blank=False, null=False)

    def __str__(self):
        return "{} {}".format(self.recipe.name, self.element)

    class Meta:
        unique_together = ("recipe", "element")
        ordering = ['order', ]


class PreparationTime(models.Model):
    text = models.CharField(max_length=32)
    min_time = models.PositiveSmallIntegerField()
    max_time = models.PositiveSmallIntegerField()
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

www/api/views.py
from rest_framework import viewsets

from api import serializers
from recipes import models


class RecipeViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.Recipe.objects.all()
    serializer_action_classes = dict(
        list=serializers.RecipeListSerializer,
        retrieve=serializers.RecipeDetailSerializer,
    )

    def get_serializer_class(self):
        return self.serializer_action_classes[self.action]


class ElementViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.Element.objects.all()
    serializer_class = serializers.ElementSerializer

www/recipes/views.py
from django.http import HttpResponseRedirect
from django.views.generic import DetailView, ListView

from recipes import models


class RecipeListView(ListView):
    model = models.Recipe

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['elements'] = models.Element.objects.all()
        return context


class RecipeDetailView(DetailView):
    model = models.Recipe

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        slug_from_url = self.kwargs.get(self.slug_url_kwarg, '')
        if obj.slug != slug_from_url:
            return HttpResponseRedirect(obj.get_absolute_url())
        return super(RecipeDetailView, self).dispatch(request, *args, **kwargs)

www/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{#        <link rel="stylesheet" href="https://unpkg.com/vue-multiselect@2.1.0/dist/vue-multiselect.min.css">#}
        <script src="https://unpkg.com/htmx.org@2.0.3" integrity="sha384-0895/pl2MU10Hqc6jd4RvrthNlDiE9U1tWmX7WRESftEDRosgxNsQG/Ze9YMRzHq" crossorigin="anonymous"></script>
        <title>{% block title %}Recipes application{% endblock title %}</title>
    </head>

    <body>
        {% block content %}
        {% endblock content %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>    </body>
    </body>
</html>

www/templates/recipes/recipe_detail.html
{% extends "base.html" %}

{% block title %}{{ recipe.name }}{% endblock title %}

{% block content %}
    <div class="row">
        <div class="row">
            <div class="col-md-3">
                <a href="{% url 'recipes:list' %}">All recipes</a>
                <br><br><br>
                <h2>Składniki</h2>
                <ul>
                    {% for ingredient in recipe.ingredient_set.all %}
                        <li>
                            {{ ingredient.element.name }}: {{ ingredient.quantity.name }} {{ ingredient.amount }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-6">
                <h1>{{ recipe.name }}</h1>
                <img src="{{ recipe.image.crop.400x400 }}">
                {{ recipe.content }}
                <div class="row">
                    <div class="col-md-10 offset-md-1">
                        {% for section in recipe.sections.all %}
                            <div>
                                <h3>{{ section.title }}</h3>
                                <img src="{{ section.image.crop.400x400 }}"/><br/>
                                {{ section.content }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                Czas przygotowania: {{ recipe.preparation_time }} minut
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 offset-md-9">
                Autor: {{ recipe.author_name }}
            </div>
        </div>
    </div>
{% endblock content %}

www/templates/recipes/recipe_list.html
{% extends "base.html" %}

{% block title %}Recipes list{% endblock title %}

{% block content %}
    <div>
        <label for="elements">Choose element(s)</label>
        <select name="elements" id="elements" multiple>
            {% for element in elements %}
                <option value="{{ element.slug }}">{{ element.name }}</option>
            {% endfor %}
        </select>

        <h1>Recipes</h1>
        <ul id="recipes">
            {% for recipe in recipe_list %}
                <li>
                    <a href="{{ recipe.get_absolute_url }}">
                        <div class="image"><img src="{{ recipe.image.crop.160x120 }}"/></div>
                        <div class="headline">{{ recipe.name }}</div>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}